### ISSUE TITLE
Be consistent with size names

### ISSUE THREAD

**Issue by moodysalem** [FastModelSports/fastmodel-layout-components#10]
@zpfled The modal has sizes of 'sm' and 'lg' (not sure why this array is a property of the modal class) and the button has sizes of 'small', 'medium', and 'large'

**Comment by moodysalem** [comment]
IMO we should stick with the bootstrap convention of sm, md, lg, xl

**Comment by zpfled** [comment]
I prefer "small" to "sm", and it reduces the chance of a stray bootstrap style influencing our styles (although that is unlikely since I use capitalized Component names to prefix my classes, and bootstrap doesn't). Full words are nicer to read than abbreviations, esp when the full words are short. It's not a big deal here, though...I suppose 'sm' is pretty normal outside of Bootstrap, too. Like with t-shirts. I'll change it.

I made the size array a property of the Modal class so that our demo page can be self-maintaining.

```
Modal.sizes.map((size) => { ... render a modal of this size ... })

```
keeps our demo page current if we make changes to size, or type (for buttons).

**Comment by zpfled** [comment]
done
