### ISSUE TITLE
The backdrop property is not being used in the modal

### ISSUE THREAD

**Issue by moodysalem** [FastModelSports/fastmodel-layout-components#8]
@zpfled the backdrop property came from bootstrap's modal backdrop option

currently it's not being used at all
Includes a modal-backdrop element. Alternatively, specify static for a backdrop which doesn't close the modal on click.

**Comment by zpfled** [comment]
I have it set so that if showClose is true, then clicking outside the modal will dismiss it. I am not married to that idea, it just made sense to me ('showClose=false' modals require an action, so we don't let you dismiss without making a choice--whereas 'showClose=true' modals can be dismissed any old way). 

But I do think that a configurable backdrop option is superfluous. Seems like a recipe for inconsistent modal behavior across the site. Is there a reason that we need the backdrop option to be configurable?

**Comment by moodysalem** [comment]
If we are going to choose a single behavior, then it should be the existing default behavior of 'static'

The backdrop is a big target and makes it very easy to accidentally close a modal

In places where you're only viewing information, accidentally closing the modal via the backdrop is not a big deal, and it's a convenience to be able to do that. In places where you are editing data, you shouldn't be able to accidentally close the modal by clicking the backdrop

**Comment by zpfled** [comment]
I put in a default static, and if backdrop is static, the modal won't close on backdrop click.

That's all there is to it at this point.
